// Prácticas de Progreso — cada 14 días
// Este archivo se puede editar o reemplazar solo, sin tocar el resto del curso.
// Cada entrada tiene: 15 palabras, 10 preguntas abiertas (no se califican), 10 frases para traducir.
const practicasProgreso = {
  14: {
    palabras: [
      {es:"gracias", en:"thank you"},
      {es:"cómo te llamas", en:"what's your name"},
      {es:"vendemos", en:"we sell"},
      {es:"trabajo en", en:"I work at"},
      {es:"cuántas cajas", en:"how many boxes"},
      {es:"programar una reunión", en:"to schedule a meeting"},
      {es:"cómo te va", en:"how are you doing"},
      {es:"todo está bien", en:"everything's ok"},
      {es:"hasta la próxima", en:"until next time"},
      {es:"puedes explicar", en:"can you explain"},
      {es:"grande", en:"big"},
      {es:"sigue adelante", en:"keep going"},
      {es:"cocina", en:"kitchen"},
      {es:"me despierto", en:"I wake up"},
      {es:"turno", en:"shift"}
    ],
    preguntas: [
      "How do you greet someone in the morning?",
      "What is your name, and where do you work?",
      "What time do you usually wake up?",
      "Do you prefer coffee or water in the morning?",
      "What do you do first when you arrive at the office?",
      "How many days a week do you work?",
      "Is your workday long or short?",
      "What do you say when you finish a meeting?",
      "Do you take a break during the day?",
      "How do you feel today — tired or energetic?"
    ],
    frases: [
      {es:"Bienvenido a la Tienda del Dragón, la mejor tienda del reino.", en:"Welcome to the Dragon Store, the best shop in the kingdom."},
      {es:"¿Estás disponible el lunes, en el año 3000?", en:"Are you available on Monday, in the year 3000?"},
      {es:"Gracias, y nos vemos pronto en las nubes.", en:"Thank you, and see you soon in the clouds."},
      {es:"Es increíblemente pesado porque está hecho de metal sólido.", en:"It's incredibly heavy because it's made of solid metal."},
      {es:"El estante tiene mil llaves mágicas.", en:"The shelf holds a thousand magic keys."},
      {es:"Finalmente, termino de trabajar y descanso dentro de una nube.", en:"Finally, I finish work and rest inside a cloud."},
      {es:"Necesito ayuda ahora mismo, tengo una reunión hoy.", en:"I need help right now, I have a meeting today."},
      {es:"¿Dónde está el baño? Un dragón tan grande necesita uno gigante.", en:"Where is the bathroom? A dragon this big needs a very big bathroom."},
      {es:"Buenas tardes, humanitos, buenas noches, amigos.", en:"Good afternoon, tiny humans, goodbye and good night, my friends."},
      {es:"El placer es mío, humano.", en:"The pleasure is mine, human."}
    ]
  },
  28: {
    palabras: [
      {es:"enviar", en:"to send"},
      {es:"martillo", en:"hammer"},
      {es:"mascota", en:"pet"},
      {es:"vecino", en:"neighbor"},
      {es:"a propósito", en:"by the way"},
      {es:"arroz", en:"rice"},
      {es:"limpiar", en:"to clean"},
      {es:"fin de semana", en:"weekend"},
      {es:"más caro", en:"more expensive"},
      {es:"una vez más", en:"one more time"},
      {es:"próxima unidad", en:"next unit"},
      {es:"presupuesto", en:"budget"},
      {es:"total general", en:"grand total"},
      {es:"horario de atención", en:"business hours"},
      {es:"número de rastreo", en:"tracking number"}
    ],
    preguntas: [
      "What tasks do you usually do at work every day?",
      "What tools do you have in your office or home?",
      "Do you have a pet? What kind?",
      "How is your relationship with your neighbors?",
      "What do you usually eat for lunch?",
      "How do you organize your warehouse or workspace?",
      "What do you do on the weekend?",
      "How do you compare prices before buying something?",
      "What time do your business hours start and end?",
      "Have you ever had a delayed shipment? What happened?"
    ],
    frases: [
      {es:"Si algo se rompe, lo arregla al instante y entrega la solución por correo de dragón.", en:"If something breaks, it fixes it instantly and delivers the fix by dragon mail."},
      {es:"¡El compromiso es nuestro superpoder!", en:"Commitment is our superpower!"},
      {es:"Si alguna vez hay una queja, los dragones siempre encuentran una solución.", en:"If there's ever a complaint, dragons always find a solution."},
      {es:"Tomate tu tiempo — ya casi llegamos, pero todavía el tesoro no llegó.", en:"Take your time — we're almost there, but still, the treasure hasn't arrived yet."},
      {es:"¿Dónde está el menú? Espero que tenga mil páginas, con una reserva para todo el reino.", en:"Where is the menu? I hope it has a thousand pages, with a reservation for the whole kingdom."},
      {es:"Si falta una o está dañada, exige una devolución y actualiza la lista al instante.", en:"If one is missing or damaged, it demands a return and updates the list instantly."},
      {es:"Planeo disfrutar cada momento antes de volver al trabajo la próxima semana.", en:"I plan to enjoy every single moment before I return to work next week."},
      {es:"La oferta del mago es el mejor trato — negociemos un contrato mágico.", en:"The wizard's offer is the best deal — let's negotiate a magical contract."},
      {es:"Sumemos todo: el total general es más grande que la luna.", en:"Let's add it all up: the grand total is bigger than the moon."},
      {es:"La llegada estimada y el número de rastreo están escritos en polvo de estrellas.", en:"The estimated arrival and tracking number are written in stardust."}
    ]
  },
  42: {
    palabras: [
      {es:"vencido", en:"overdue"},
      {es:"condiciones de pago", en:"payment terms"},
      {es:"saldo pendiente", en:"balance due"},
      {es:"déjame ver", en:"let me see"},
      {es:"prioridad máxima", en:"top priority"},
      {es:"transferencia bancaria", en:"bank transfer"},
      {es:"reembolso", en:"refund"},
      {es:"al por mayor", en:"wholesale"},
      {es:"trato cerrado", en:"deal closed"},
      {es:"kilogramo", en:"kilogram"},
      {es:"quisiera pedir", en:"I would like to order"},
      {es:"confirmar asistencia", en:"confirm attendance"},
      {es:"dividir la cuenta", en:"split the bill"},
      {es:"receta", en:"recipe"},
      {es:"actualización de estado", en:"status update"}
    ],
    preguntas: [
      "What is your preferred payment method?",
      "Do you usually pay in cash or by card?",
      "What is your top priority at work this week?",
      "Have you ever negotiated a lower price for something?",
      "What's your favorite dish to order at a restaurant?",
      "Do you have any food allergies?",
      "How do you usually split the bill with friends?",
      "Do you enjoy cooking? What's your favorite recipe?",
      "Have you ever had connection problems during a video call?",
      "What do you usually eat for breakfast?"
    ],
    frases: [
      {es:"En noviembre y diciembre, llega la fecha de vencimiento del tesoro.", en:"In November and December, the treasure's due date arrives."},
      {es:"Si el dragón necesita más tiempo, le damos una prórroga — un período de gracia de mil años.", en:"If the dragon needs more time, we grant an extension — a grace period of one thousand years."},
      {es:"Nuestro proveedor preferido es un mago de mil años, y la lista de espera tiene treinta mil dragones.", en:"Our preferred supplier is a thousand-year-old wizard, and the waiting list has thirty thousand dragons."},
      {es:"Esta es mi oferta final, dragón — trato cerrado.", en:"This is my final offer, dragon — deal closed."},
      {es:"Nos vemos en la unidad cuatro, donde te esperan nuevos dragones y tesoros más grandes.", en:"See you in unit four, where new dragons and greater treasures await."},
      {es:"Por favor reservá el único horario en que las dos lunas se alinean — revisá la agenda.", en:"Please book the only time slot when the two moons align — check the agenda."},
      {es:"Resumamos y cerremos antes de que el castillo desaparezca.", en:"Let's summarize and wrap up before the castle disappears."},
      {es:"Ensayalo frente a mil dragones antes del show real.", en:"Rehearse it in front of a thousand dragons before the real show."},
      {es:"La conexión es débil en la luna — iniciá sesión de nuevo, y no te olvides de cerrar sesión antes del eclipse.", en:"The connection is weak on the moon — sign in again, and do not forget to sign off before the eclipse."},
      {es:"¿Vamos bien encaminados, o atrasados en el hito del tesoro?", en:"Are we on track, or behind schedule on the treasure milestone?"}
    ]
  },
  56: {
    palabras: [
      {es:"certificado médico", en:"medical certificate"},
      {es:"apto para viajar", en:"fit to travel"},
      {es:"resfriado", en:"headache"},
      {es:"probarse", en:"to try on"},
      {es:"te queda bien", en:"does it fit"},
      {es:"cotización formal", en:"formal quote"},
      {es:"regatear", en:"to bargain"},
      {es:"recargo por mora", en:"late fee"},
      {es:"comprobante de compra", en:"proof of purchase"},
      {es:"garantía", en:"warranty"},
      {es:"insertar la tarjeta", en:"insert the card"},
      {es:"carrito de compras", en:"shopping cart"},
      {es:"de ahora en adelante", en:"from now on"},
      {es:"pendiente de aprobación", en:"pending approval"},
      {es:"comparación de precios", en:"price comparison"}
    ],
    preguntas: [
      "Have you ever been sick before a business trip? What did you do?",
      "What symptoms make you decide to see a doctor?",
      "Do you prefer shopping in a physical store or online?",
      "Have you ever negotiated the price of clothing or shoes?",
      "What do you do if a product you bought doesn't work?",
      "How do you usually pay for things — card or cash?",
      "Have you ever compared prices between stores before buying?",
      "What would you do if you received a defective product?",
      "Do you check customer reviews before buying online?",
      "How do you feel about return policies in your country?"
    ],
    frases: [
      {es:"¿Estoy apto para viajar? Sí, después de esta vacunación contra la gripe de dragón.", en:"Am I fit to travel? Yes, after this vaccination against dragon flu!"},
      {es:"Dejame probarme esta armadura mágica, ¿me queda bien, o es muy grande?", en:"Let me try on this magic armor — does it fit, or is it too big?"},
      {es:"Aquí tienes tu cotización formal, adjunta en este pergamino mágico.", en:"Here is your formal quote, attached to this magic scroll."},
      {es:"¿Puedes bajar el precio, dragón? Regateemos.", en:"Can you lower the price, dragon? Let's bargain!"},
      {es:"Pagá tarde, y hay un recargo por mora del tamaño de un dragón.", en:"Pay late, and there's a dragon-sized late fee!"},
      {es:"Acá está mi comprobante de compra, ¿puedo cambiarlo por uno nuevo?", en:"Here is my proof of purchase — can I exchange it for a new one?"},
      {es:"¿Esta espada mágica está cubierta por la garantía, o no está cubierta?", en:"Is this magic sword covered by warranty, or not covered?"},
      {es:"Deslizá la tarjeta, o insertá la tarjeta — el dragón acepta las dos.", en:"Swipe the card, or insert the card — the dragon accepts both!"},
      {es:"Agrega al carrito el castillo volador, y escribe tu dirección de envío en las nubes.", en:"Add to cart the flying castle, and type your shipping address in the clouds."},
      {es:"Que yo sepa, para ser honesto, los dragones nunca mienten.", en:"As far as I know, to be honest, dragons never lie."}
    ]
  },
  70: {
    palabras: [
      {es:"el más barato", en:"cheapest"},
      {es:"vale la pena", en:"worth it"},
      {es:"decisión final", en:"final decision"},
      {es:"producto defectuoso", en:"faulty product"},
      {es:"número de caso", en:"case number"},
      {es:"dobla a la izquierda", en:"turn left"},
      {es:"sigue derecho", en:"go straight"},
      {es:"está lejos", en:"it's far"},
      {es:"recogida", en:"pickup"},
      {es:"está en tránsito", en:"in transit"},
      {es:"entregado", en:"delivered"},
      {es:"transportista", en:"carrier"},
      {es:"aduana", en:"customs"},
      {es:"país de origen", en:"country of origin"},
      {es:"zona de reparto", en:"delivery zone"}
    ],
    preguntas: [
      "How do you compare prices before making a big purchase?",
      "Have you ever filed a complaint about a product? What happened?",
      "How do you usually give someone directions in your city?",
      "What form of transportation do you use most often?",
      "Have you ever traveled by airplane? Where did you go?",
      "How do you usually track a package you're waiting for?",
      "Do you live near a busy street with a lot of traffic?",
      "Have you ever rented a car? What was the experience like?",
      "What do you do if a delivery is late?",
      "How far do you live from your workplace?"
    ],
    frases: [
      {es:"Me quejo, esto no funciona — quiero un reembolso por este producto defectuoso.", en:"I need to complain — this doesn't work, I want a refund for this faulty product."},
      {es:"Progreso constante, valiente héroe — no te rindas, ya casi estás en la unidad seis.", en:"Steady progress, brave hero — don't give up, you are almost at unit six!"},
      {es:"Disculpe, ¿dónde está el correo de dragones? ¿Cómo llego ahí?", en:"Excuse me, where is the dragon post office? How do I get there?"},
      {es:"Dobla a la izquierda en el volcán, después sigue derecho pasando el arcoíris.", en:"Turn left at the volcano, then go straight past the rainbow!"},
      {es:"Rastreemos un pedido — hacé clic en el enlace de rastreo, dragón.", en:"Let's track an order — click the tracking link, dragon!"},
      {es:"Está en tránsito, en reparto, y entregado — todo en un segundo.", en:"It's in transit, out for delivery, and delivered — all in one second!"},
      {es:"Elijamos un transportista — esta empresa de transporte vuela con dragones.", en:"Let's choose a carrier — this shipping company flies with dragons!"},
      {es:"La aduana quiere saber: ¿importas o exportas frijoles mágicos?", en:"Customs wants to know: do you import or export magic beans?"},
      {es:"El arancel y la declaración de aduana dependen del país de origen.", en:"The tariff and customs declaration depend on the country of origin!"},
      {es:"Hasta la zona más alejada tiene entrega el mismo día, en dragón.", en:"Even the most remote area gets same-day delivery, by dragon!"}
    ]
  },
  84: {
    palabras: [
      {es:"norte", en:"north"},
      {es:"centro", en:"downtown"},
      {es:"ruta óptima", en:"optimal route"},
      {es:"reserva", en:"reservation"},
      {es:"recepción", en:"front desk"},
      {es:"habitación doble", en:"double room"},
      {es:"viaje de negocios", en:"business trip"},
      {es:"servicio a la habitación", en:"room service"},
      {es:"emergencia", en:"emergency"},
      {es:"seguro de viaje", en:"travel insurance"},
      {es:"dolor de cabeza", en:"headache"},
      {es:"apto para viajar", en:"fit to travel"},
      {es:"pronóstico", en:"forecast"},
      {es:"contraseña", en:"password"},
      {es:"compartir pantalla", en:"share screen"}
    ],
    preguntas: [
      "What's the weather like in your city today?",
      "Have you ever stayed in a hotel for a business trip?",
      "Do you know how to get to the nearest hospital from your home?",
      "What do you usually do when you have a headache?",
      "Do you prefer working with a laptop or a desktop computer?",
      "How often do you check your social media?",
      "Have you ever had a technical problem during a video call?",
      "Do you keep your wifi password private, or share it easily?",
      "Do you enjoy traveling? What was your last trip?",
      "How do you usually handle stress at work?"
    ],
    frases: [
      {es:"Vuela al norte, sur, este, u oeste — ¿por dónde queda el castillo?", en:"Fly north, south, east, or west — which way to the castle?"},
      {es:"¡Bienvenido al Hotel Dragón! ¿Tienes una reserva, valiente viajero?", en:"Welcome to the Dragon Hotel! Do you have a reservation, brave traveler?"},
      {es:"Quisiera reservar una habitación para mi viaje de negocios, a la tarifa corporativa, por favor.", en:"I would like to book a room for my business trip, at the corporate rate, please."},
      {es:"Necesito pedir servicio a la habitación — ¡una montaña de panqueques!", en:"I need to order room service — a mountain of pancakes!"},
      {es:"¡Emergencia! Llamen al hospital — el dragón se comió una montaña entera.", en:"Emergency! Call the hospital — the dragon ate a whole mountain."},
      {es:"¿Mi seguro de viaje cubre esto?", en:"Does my travel insurance cover this?"},
      {es:"Tengo dolor de cabeza, dolor de estómago, y tos — todo al mismo tiempo.", en:"I have a headache, a stomachache, and a cough — all at the same time."},
      {es:"¿Estoy apto para viajar? Sí, después de esta vacunación contra la gripe de dragón.", en:"Am I fit to travel? Yes, after this vaccination against dragon flu!"},
      {es:"El pronóstico dice tormenta — reprogramemos por el clima.", en:"The forecast says a storm — let's reschedule due to weather."},
      {es:"¿Puedes compartir pantalla? Vamos a la sala de grupos a planear el tesoro.", en:"Can you share screen? Let's go to the breakout room to plan the treasure!"}
    ]
  },
  98: {
    palabras: [
      {es:"currículum", en:"resume"},
      {es:"entrevista de trabajo", en:"job interview"},
      {es:"fortalezas", en:"strengths"},
      {es:"cuéntame sobre ti", en:"tell me about yourself"},
      {es:"trabaja bien en equipo", en:"team player"},
      {es:"negociar el salario", en:"to negotiate salary"},
      {es:"evento de networking", en:"networking event"},
      {es:"presentación breve", en:"elevator pitch"},
      {es:"hablar en público", en:"public speaking"},
      {es:"puntos clave", en:"key points"},
      {es:"contrato", en:"contract"},
      {es:"firmar", en:"to sign"},
      {es:"asesor legal", en:"legal advisor"},
      {es:"cultura de oficina", en:"office culture"},
      {es:"horario flexible", en:"flexible hours"}
    ],
    preguntas: [
      "What are your greatest strengths in a work environment?",
      "How would you describe yourself in a job interview?",
      "Have you ever attended a networking event? What was it like?",
      "Do you feel comfortable with public speaking?",
      "What makes a good team player, in your opinion?",
      "Have you ever negotiated your salary? How did it go?",
      "What does your ideal office culture look like?",
      "Do you prefer working fixed hours or flexible hours?",
      "Have you ever read a contract carefully before signing?",
      "What is the most important quality in a leader?"
    ],
    frases: [
      {es:"Quisiera postularme a un trabajo en la Empresa Dragón — acá está mi currículum y carta de presentación.", en:"I would like to apply for a job at the Dragon Company — here is my resume and cover letter."},
      {es:"¿Cuáles son tus fortalezas y debilidades, candidato?", en:"What are your strengths and weaknesses, candidate?"},
      {es:"Cuéntame sobre ti, dragón — ¿cuál es tu experiencia previa?", en:"Tell me about yourself, dragon — what is your previous experience?"},
      {es:"Ahora, negociemos el salario — solo acepto pago en oro.", en:"Now, let's negotiate salary — I only accept payment in gold."},
      {es:"Dejame presentarme con mi presentación breve: soy un dragón de la industria del tesoro.", en:"Let me introduce myself with my elevator pitch: I am a dragon in the treasure industry."},
      {es:"Cubrí los puntos clave, usá ayudas visuales, y captá la atención del público.", en:"Cover the key points, use visual aids, and engage the audience."},
      {es:"Por favor leé el contrato con cuidado antes de firmar, dragón.", en:"Please read the contract carefully before you sign, dragon."},
      {es:"Esta cláusula es confidencial — solo el asesor legal puede leerla.", en:"This clause is confidential — only the legal advisor can read it!"},
      {es:"Nuestra cultura de oficina valora el equilibrio entre trabajo y vida.", en:"Our office culture values work-life balance."},
      {es:"Ofrecemos trabajo remoto y horario flexible — volá cuando quieras.", en:"We offer remote work and flexible hours — fly whenever you want!"}
    ]
  },
  112: {
    palabras: [
      {es:"control de calidad", en:"quality control"},
      {es:"satisfacción del cliente", en:"customer satisfaction"},
      {es:"manejo de crisis", en:"crisis management"},
      {es:"sostenibilidad", en:"sustainability"},
      {es:"licencia de exportación", en:"export license"},
      {es:"línea de producción", en:"production line"},
      {es:"recursos humanos", en:"human resources"},
      {es:"ascenso", en:"promotion"},
      {es:"cerrar un trato", en:"to close a deal"},
      {es:"comisión", en:"commission"},
      {es:"bienes raíces", en:"real estate"},
      {es:"inquilino", en:"tenant"},
      {es:"póliza de seguro", en:"insurance policy"},
      {es:"especialista", en:"specialist"},
      {es:"beca", en:"scholarship"}
    ],
    preguntas: [
      "How does your company handle customer complaints?",
      "What would you do in a crisis situation at work?",
      "Do you think sustainability is important for businesses today?",
      "Have you ever worked on a production line or in manufacturing?",
      "What benefits matter most to you in a job?",
      "Have you ever closed an important deal? What happened?",
      "Do you rent or own the place where you live?",
      "Have you ever filed an insurance claim?",
      "Do you have health insurance? What does it cover?",
      "Have you ever received a scholarship or financial aid for studying?"
    ],
    frases: [
      {es:"El control de calidad revisa cada huevo de dragón según nuestro estándar.", en:"Quality control checks every dragon egg against our standard."},
      {es:"La satisfacción del cliente es nuestra prioridad número uno.", en:"Customer satisfaction is our top priority."},
      {es:"El manejo de crisis empieza con un plan de contingencia sólido.", en:"Crisis management starts with a solid contingency plan."},
      {es:"Solo usamos fuego ecológico, impulsado por energía renovable del sol.", en:"We only use eco-friendly fire, powered by renewable energy from the sun."},
      {es:"Necesitamos una licencia de exportación, y el arancel de importación se debe pagar primero.", en:"We need an export license, and the import duty must be paid first."},
      {es:"La línea de producción funciona día y noche, convirtiendo materia prima en oro.", en:"The production line runs day and night, turning raw materials into gold."},
      {es:"Recursos humanos maneja la incorporación de cada nuevo empleado dragón.", en:"Human resources handles onboarding for every new dragon employee."},
      {es:"Cerré el trato — cumplí mi cuota, y gané mi comisión.", en:"I closed the deal — I met my quota, and earned my commission."},
      {es:"Quiero alquilar, o tal vez arrendar, un castillo en el cielo.", en:"I want to rent, or maybe lease, a castle in the sky."},
      {es:"Mi seguro de salud cubre al especialista, pero primero necesito una derivación.", en:"My health insurance covers the specialist, but I need a referral first."}
    ]
  },
  126: {
    palabras: [
      {es:"permiso", en:"permit"},
      {es:"portal en línea", en:"online portal"},
      {es:"prueba de manejo", en:"test drive"},
      {es:"opciones de financiamiento", en:"financing options"},
      {es:"empresa de mudanzas", en:"moving company"},
      {es:"lista de invitados", en:"guest list"},
      {es:"inteligencia artificial", en:"artificial intelligence"},
      {es:"ciberseguridad", en:"cybersecurity"},
      {es:"estilo de liderazgo", en:"leadership style"},
      {es:"toma de decisiones", en:"decision-making"},
      {es:"ponerse en contacto brevemente", en:"to touch base"},
      {es:"esforzarse más de lo esperado", en:"to go the extra mile"},
      {es:"acuerdo bilateral", en:"bilateral agreement"},
      {es:"posicionamiento de marca", en:"brand positioning"},
      {es:"carrito de compras", en:"shopping cart"}
    ],
    preguntas: [
      "Have you ever gone through a long government process to get a permit or document?",
      "Would you rather buy a car online or test drive it first?",
      "Have you ever hired a moving company? What was the experience like?",
      "Do you think artificial intelligence will change your industry?",
      "How would you describe your own leadership style?",
      "What does going the extra mile mean to you at work?",
      "Have you ever attended an international business meeting?",
      "What makes a brand memorable, in your opinion?",
      "Do you prefer shopping online or in physical stores?",
      "What technology trend are you most curious about right now?"
    ],
    frases: [
      {es:"Fui a la oficina gubernamental a sacar un permiso para mi castillo volador.", en:"I went to the government office to get a permit for my flying castle."},
      {es:"¡Bienvenido a la concesionaria de autos dragón! ¿Quieres una prueba de manejo?", en:"Welcome to the dragon car dealership! Would you like a test drive?"},
      {es:"La empresa de mudanzas mandó a un gigante para ayudar a embalar mi tesoro.", en:"The moving company sent a giant to help with packing my treasure!"},
      {es:"Hasta los dragones usan inteligencia artificial y aprendizaje automático ahora.", en:"Even dragons use artificial intelligence and machine learning now!"},
      {es:"Cada dragón líder necesita su propio estilo de liderazgo, y dominar la delegación.", en:"Every dragon leader needs their own leadership style, and to master delegation!"},
      {es:"Pongámonos en contacto mañana, y aseguremos que cumplamos con el plan.", en:"Let's touch base tomorrow, and make sure we follow through on the plan!"},
      {es:"Las relaciones diplomáticas mejoraron después de que firmamos un acuerdo bilateral.", en:"Diplomatic relations improved after we signed a bilateral agreement!"},
      {es:"Nuestra estrategia de marketing empieza con un posicionamiento de marca fuerte.", en:"Our marketing strategy starts with strong brand positioning!"},
      {es:"Nuestra plataforma de comercio electrónico tiene la mejor tienda en línea del cielo.", en:"Our e-commerce platform runs the best online storefront in the sky!"},
      {es:"Nuestra cultura de trabajo valora la toma de decisiones rápida, hasta durante un simulacro de incendio.", en:"Our work culture values fast decision-making, even during a fire drill!"}
    ]
  },
  140: {
    palabras: [
      {es:"dar en el clavo", en:"to hit the nail on the head"},
      {es:"modelo de suscripción", en:"subscription model"},
      {es:"franquicia", en:"franchise"},
      {es:"empresa emergente", en:"startup"},
      {es:"capital de riesgo", en:"venture capital"},
      {es:"ética empresarial", en:"business ethics"},
      {es:"junta directiva", en:"board of directors"},
      {es:"relaciones públicas", en:"public relations"},
      {es:"comunicado de prensa", en:"press release"},
      {es:"planificación de eventos", en:"event planning"},
      {es:"gestión minorista", en:"retail management"},
      {es:"experiencia del huésped", en:"guest experience"},
      {es:"industria del entretenimiento", en:"entertainment industry"},
      {es:"cabildeo", en:"lobbying"},
      {es:"cadena de suministro global", en:"global supply chain"}
    ],
    preguntas: [
      "Have you ever started a small business or side project?",
      "What ethical values matter most to you in a workplace?",
      "Have you ever attended an event that was well organized? What made it good?",
      "Do you enjoy shopping in physical retail stores?",
      "Have you ever stayed somewhere with excellent guest service?",
      "What kind of entertainment do you enjoy the most — movies, music, or games?",
      "Do you think public relations is important for a company's image?",
      "Have you ever dealt with a supply chain delay or shortage?",
      "What idiom or expression do you use often in Spanish that has no direct English translation?",
      "Would you rather work at a large corporation or a startup?"
    ],
    frases: [
      {es:"Diste en el clavo, dragón. Por fin estamos de acuerdo.", en:"You hit the nail on the head, dragon! We finally see eye to eye."},
      {es:"Nuestro modelo de suscripción nos da ingresos recurrentes cada ciclo lunar.", en:"Our subscription model gives us recurring revenue every single moon cycle!"},
      {es:"Este dragón abrió una franquicia — ahora es franquiciado de la marca Tesoro Dorado.", en:"This dragon opened a franchise — now he's a franchisee of the Golden Treasure brand!"},
      {es:"Este dragón fundó una empresa emergente — es un verdadero emprendedor.", en:"This dragon started a startup — he's a true entrepreneur!"},
      {es:"La ética empresarial y la gobernanza corporativa mantienen justo nuestro reino de dragones.", en:"Business ethics and corporate governance keep our dragon kingdom fair!"},
      {es:"Nuestro equipo de relaciones públicas maneja las relaciones con los medios de todo el reino.", en:"Our public relations team manages media relations for the entire dragon kingdom!"},
      {es:"La planificación de eventos empieza con un buen coordinador — este es un mago.", en:"Event planning starts with a good event coordinator — this one is a wizard!"},
      {es:"La gestión minorista significa vigilar la rotación de inventario todos los días.", en:"Retail management means watching inventory turnover every single day!"},
      {es:"Nuestra industria hotelera se enfoca en la experiencia del huésped sobre todo.", en:"Our hospitality industry focuses on guest experience above all!"},
      {es:"Nuestra cadena de suministro global conecta cada reino de dragones en el cielo.", en:"Our global supply chain connects every dragon kingdom in the sky!"}
    ]
  },
  154: {
    palabras: [
      {es:"huella de carbono", en:"carbon footprint"},
      {es:"reciclaje", en:"recycling"},
      {es:"bienes de consumo", en:"consumer goods"},
      {es:"espacio en la góndola", en:"shelf space"},
      {es:"ancho de banda", en:"bandwidth"},
      {es:"operador móvil", en:"mobile carrier"},
      {es:"estado físico", en:"fitness"},
      {es:"entrenador personal", en:"personal trainer"},
      {es:"boda", en:"wedding"},
      {es:"votos matrimoniales", en:"wedding vows"},
      {es:"tribunal", en:"court"},
      {es:"veredicto", en:"verdict"},
      {es:"sucursal bancaria", en:"bank branch"},
      {es:"saldo mínimo", en:"minimum balance"},
      {es:"cosecha", en:"harvest"}
    ],
    preguntas: [
      "Do you recycle at home or at work?",
      "What is your favorite way to stay in shape?",
      "Have you ever attended a wedding? What was memorable about it?",
      "Would you rather resolve a conflict in court or through a private agreement?",
      "How often do you check your bank account?",
      "Do you know anyone who works in agriculture?",
      "What brand do you feel loyal to, and why?",
      "Do you think about your carbon footprint when you shop?",
      "Have you ever had a problem with your phone's signal or data plan?",
      "What does a healthy work-life balance look like for you?"
    ],
    frases: [
      {es:"Medimos nuestra huella de carbono, y cada castillo tiene un programa de reciclaje.", en:"We measure our carbon footprint, and every castle has a recycling program."},
      {es:"Nuestra empresa de bienes de consumo tiene un portafolio enorme.", en:"Our consumer goods company has a huge brand portfolio."},
      {es:"Nuestra estrategia de marca global aseguró el mejor espacio en góndola en cada reino.", en:"Our global brand strategy secured the best shelf space in every kingdom!"},
      {es:"Nuestra infraestructura de red tiene ancho de banda ilimitado, gracias al poder de fuego de dragón.", en:"Our network infrastructure has unlimited bandwidth, thanks to dragon-fire power!"},
      {es:"Este dragón se toma el estado físico en serio — sacó una membresía en el gimnasio del volcán.", en:"This dragon takes fitness seriously — he got a gym membership at the volcano gym!"},
      {es:"La boda de dragones fue hermosa — el novio respiró fuego dorado para la novia.", en:"The dragon wedding was beautiful — the groom breathed golden fire for the bride!"},
      {es:"Este dragón fue a tribunal — el juez escuchó con atención a las dos partes.", en:"This dragon went to court — the judge listened carefully to both sides!"},
      {es:"El jurado llegó a un veredicto después del largo proceso legal.", en:"The jury reached a verdict after the long legal proceedings."},
      {es:"Fui a la sucursal bancaria, y el cajero me ayudó a evitar un sobregiro.", en:"I went to the bank branch, and the teller helped me avoid an overdraft!"},
      {es:"Este dragón estudió agricultura, y cultiva el cultivo más grande del reino.", en:"This dragon studied agriculture, and grows the biggest crop in the kingdom!"}
    ]
  },
  168: {
    palabras: [
      {es:"industria de la moda", en:"fashion industry"},
      {es:"desfile de moda", en:"runway show"},
      {es:"casi llegamos", en:"almost there"},
      {es:"industria farmacéutica", en:"pharmaceutical industry"},
      {es:"efectos secundarios", en:"side effects"},
      {es:"desarrollador de juegos", en:"game developer"},
      {es:"comunidad de jugadores", en:"gaming community"},
      {es:"organización sin fines de lucro", en:"non-profit organization"},
      {es:"recaudación de fondos", en:"fundraising campaign"},
      {es:"industria editorial", en:"publishing industry"},
      {es:"sistema de vigilancia", en:"surveillance system"},
      {es:"protocolo de emergencia", en:"emergency protocol"},
      {es:"planificación urbana", en:"urban planning"},
      {es:"salud mental", en:"mental health"},
      {es:"equipo remoto", en:"remote team"}
    ],
    preguntas: [
      "Do you follow fashion trends, or do you have your own style?",
      "Have you ever taken medicine and experienced side effects?",
      "Do you enjoy video games? What kind do you prefer?",
      "Have you ever donated to a charity or non-profit organization?",
      "Do you prefer reading physical books or ebooks?",
      "How important is security to you when traveling?",
      "What do you think makes a city well-planned?",
      "How do you take care of your mental health?",
      "Have you ever worked remotely? What was the experience like?",
      "What industry would you like to work in if you could choose any?"
    ],
    frases: [
      {es:"A la industria de la moda le encantan las escamas de dragón — un diseñador hizo un desfile entero con ellas.", en:"The fashion industry loves dragon scales — one designer made an entire runway show from them!"},
      {es:"La industria farmacéutica hizo un ensayo clínico de una nueva poción de sanación de dragones.", en:"The pharmaceutical industry ran a clinical trial on a new dragon healing potion!"},
      {es:"Este dragón trabaja en la industria de videojuegos — es un desarrollador con mucho talento.", en:"This dragon works in the gaming industry — he's a talented game developer!"},
      {es:"Este dragón dirige una organización sin fines de lucro — una obra de caridad de verdad.", en:"This dragon runs a non-profit organization — a true charity of the heart!"},
      {es:"Este dragón trabaja en la industria editorial — escribió un manuscrito sobre la caza de tesoros.", en:"This dragon works in the publishing industry — he wrote a manuscript about treasure hunting!"},
      {es:"La industria de la seguridad instaló un sistema de vigilancia en todo el castillo.", en:"The security industry installed a surveillance system around the whole castle!"},
      {es:"La planificación urbana diseñó una ciudad donde dragones y humanos viven juntos.", en:"Urban planning designed a city where dragons and humans live together!"},
      {es:"Nuestra empresa dragón se preocupa por la salud mental — tenemos un programa de bienestar.", en:"Our dragon company cares about mental health — we have a wellness program!"},
      {es:"Nuestro equipo remoto abarca cada reino — la colaboración virtual es clave.", en:"Our remote team spans every kingdom — virtual collaboration is key!"},
      {es:"Solo faltan doce días, y la unidad final se acerca.", en:"Only twelve days left, and the final unit is ahead!"}
    ]
  }
};
